services:
  array-env-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgresql/data
    depends_on:
      - web
  array-env-web:
    image: nginx:latest
    ports:
      - "8080:80"